# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

ics:
  secret: "secret"

provisioning:
  config:
    nubusBaseUrl: "http://nubus"
    keycloak:
      username: "kc_user"
      password: "keycloak"
      realm: "keycloak"
      url: "http://keycloak"
      connection:
        baseUrl: "http://keycloak"
        host: "keycloak"
        port: 42

    ics_client:
      clientSecret: "secret"
...
